Document: fk-ops-collectd
Title: Debian fk-ops-collectd Manual
Author: <insert document author here>
Abstract: This manual describes what fk-ops-collectd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fk-ops-collectd/fk-ops-collectd.sgml.gz

Format: postscript
Files: /usr/share/doc/fk-ops-collectd/fk-ops-collectd.ps.gz

Format: text
Files: /usr/share/doc/fk-ops-collectd/fk-ops-collectd.text.gz

Format: HTML
Index: /usr/share/doc/fk-ops-collectd/html/index.html
Files: /usr/share/doc/fk-ops-collectd/html/*.html
